### ISSUE TITLE
Is it intentional to install fuzz/framer/output/* since 0.14.1?

### ISSUE THREAD

**Issue by sunpoet** [socketry/protocol-http2#6]
protocol-http2 0.14.1 installs fuzz/framer/output/* because of spec.files change in 8769e9f8dfcb95c6e7bd015002a74a82bb14a83f. Is it intentional?

**Comment by Luckless** [comment]
Yeah, I'm having some issues installing this on windows 10 for puppet rspec stuff:

```
Installing protocol-http2 0.14.1
Errno::EINVAL: Invalid argument @ rb_sysopen -
C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/protocol-http2-0.14.1/fuzz/framer/output/crashes/id:000000,sig:10,src:000007,op:havoc,rep:32
An error occurred while installing protocol-http2 (0.14.1), and Bundler cannot
continue.
Make sure that `gem install protocol-http2 -v '0.14.1' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  github_changelog_generator was resolved to 1.15.1, which depends on
    async-http-faraday was resolved to 0.9.0, which depends on
      async-http was resolved to 0.52.4, which depends on
        protocol-http2
```

**Comment by ioquatix** [comment]
Haha, no, and I'm already fixing this on other gems but have not got around to this yet.

I'll sort this out on the next release should be this week.

**Comment by kenhys** [comment]
@ioquatix 
Are there any blockers to release the next release?

**Comment by ashie** [comment]
@ioquatix Any progress?

**Comment by ioquatix** [comment]
Let me check...

**Comment by ioquatix** [comment]
Okay, I've released an update, thanks for bumping the issue, I've been pretty overloaded the past 6 months with Ruby 3.0 release.

**Comment by ashie** [comment]
I've confirmed that protocol-http2-0.14.2 can be installed successfully on Windows. Thanks!

**Comment by sunpoet** [comment]
Thank you, @ioquatix.
